# Generated by Django 4.2.6 on 2023-10-31 10:55

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
