# Generated by Django 4.2.6 on 2023-11-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_remove_note_parent_category_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
