# Generated by Django 4.2.6 on 2024-01-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_item_options_item_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('due_date', '-date_created')},
        ),
        migrations.AlterField(
            model_name='item',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todo_app.todo'),
        ),
    ]
